### ISSUE TITLE
Blank screen after installing on le potato

### ISSUE THREAD

**Issue by nikunj915** [avarakin/AstroPiMaker4#4]
I tried installing on a le potato and after rebooting I just get a blank screen without any login prompt. I started with Ubuntu 22.04 and followed the installation steps.

**Comment by avarakin** [comment]
It is a known issue. I do not use physical screen, instead I use virtual screen and connect to it using vnc.
You can try the following solution:
https://hub.libre.computer/t/x11-does-not-start-on-le-potato-based-on-base-image/985
Please let me know if it worked

**Comment by nikunj915** [comment]
Thank you, that worked. I just had to copy .conf files and after I rebooted I was able to view the screen.
Here's what I did:

```
git clone https://github.com/libre-computer-project/libretech-raspbian-portability.git lrp
mkdir -p /usr/share/X11/xorg.conf.d
cp lrp/apps/xorg/10-*.conf /usr/share/X11/xorg.conf.d
```
